server:
  port: 8080
  servlet:
    context-path: /bootPipeline
spring:
  application:
    name: bootPipeline
management:
  endpoints:
    web:
      exposure:
        include:
          - "beans"
          - "health"
          - "info"